name: binary_vae
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36hef1b27d_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.18.1=py36hde5b4d6_1
  - openssl=1.1.1d=h7b6447c_3
  - pcre=8.43=he6710b0_0
  - pip=20.0.2=py36_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - setuptools=45.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - wheel=0.34.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.0.0
    - chardet==3.0.4
    - cloudpickle==1.2.2
    - decorator==4.4.1
    - gast==0.2.2
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - numpy==1.18.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - tensorflow-probability==0.9.0
    - termcolor==1.1.0
    - urllib3==1.25.8
    - werkzeug==0.16.1
    - wrapt==1.11.2

